apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cpd-instance-channel
  namespace: cpd-instance
spec:
  pathname: 'https://github.com/tosin2013/acm-cloudpak-for-data.git'
  type: GitHub