apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ibm-common-services-deployment
  namespace: ibm-common-services
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - ibm-common-services-deployment
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription