apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ibm-common-services-cluster1-sub
  namespace: ibm-common-services
  labels:
    deployment: ibm-common-services-deployment
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: clusters/cluster1
spec:
  channel:  ibm-common-services/ibm-common-services-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster1