---
- name: Create ibm-common-services namespace
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ibm-common-services
  tags: deploy 
- name: Create channel for ibm-common-services
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: apps.open-cluster-management.io/v1
      kind: Channel
      metadata:
        name: ibm-common-services-channel
        namespace: ibm-common-services
      spec:
        pathname: 'https://github.com/tosin2013/acm-cloudpak-for-data.git'
        type: GitHub
  tags: deploy 
- name: Create Application for ibm-common-services
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: app.k8s.io/v1beta1
      kind: Application
      metadata:
        name: ibm-common-services-deployment
        namespace: ibm-common-services
      spec:
        selector:
          matchExpressions:
            - key: deployment  
              operator: In
              values:
              - ibm-common-services-deployment
        componentKinds:
        - group: app.ibm.com/v1alpha1
          kind: Subscription
  tags: deploy 
- name: Create PlacementRule for ibm-common-services
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: apps.open-cluster-management.io/v1
      kind: PlacementRule
      metadata:
        name: local-cluster
        namespace: ibm-common-services
      spec:
        clusterSelector:
          matchLabels:
            name: local-cluster
  tags: local-cluster 
- name: Create Subscription for ibm-common-services
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: apps.open-cluster-management.io/v1
      kind: Subscription
      metadata:
        name: ibm-common-services-local-cluster-sub
        namespace: ibm-common-services
        labels:
          deployment: ibm-common-services-deployment
        annotations:
          apps.open-cluster-management.io/github-branch: main
          apps.open-cluster-management.io/github-path:  clusters/local-cluster
      spec:
        channel: ibm-common-services/ibm-common-services-channel
        placement: 
          placementRef: 
            kind: PlacementRule
            name: local-cluster
  tags: local-cluster 
- name: Wait for Cloud Pak for Data Platform Operator CRD to be defined
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    host: "{{ openshift_url }}"
    wait: yes
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    name: "{{ cpdplatformoperatorCSV }}"
    wait_sleep: 10
    wait_timeout: 60
  tags: 
  - local-cluster 
- name: Wait for Cloud Pak for Data Platform Operator CRD to be ready
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    host: "{{ openshift_url }}"
    wait: yes
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    field_selectors:
      - status.phase=Succeeded
  tags: 
  - local-cluster 
# Example showing how to end the play for specific targets
#- name: End the play for hosts that run CentOS 6
#  meta: end_host
- name: Wait for IBM Cloud Pak foundational services  to be defined
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    wait: yes
    name: "{{ ibmcommonserviceoperatorCSV }}"
  tags: 
    - local-cluster 
- name: Wait for IBM Cloud Pak foundational services to be ready
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    wait: yes
    name: "{{ ibmcommonserviceoperatorCSV }}"
    field_selectors:
      - status.phase=Succeeded
  tags: 
    - local-cluster 
- name: Wait for IBM NamespaceScope Operator to be defined
  kubernetes.core.k8s_info:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    wait: yes
    name: "{{ ibmamespacescopeoperatorCSV }}"
  tags: 
    - local-cluster 
- name: Wait for IBM NamespaceScope Operator  to be ready
  kubernetes.core.k8s_info:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    wait: yes
    name: "{{ ibmamespacescopeoperatorCSV }}"
    field_selectors:
      - status.phase=Succeeded
  tags: 
    - local-cluster 
- name: Wait for Operand Deployment Lifecycle Manager CRD to be defined
  kubernetes.core.k8s_info:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    name: "{{ operanddeploymentlifecyclemanagerCSV }}"
  tags: 
    - local-cluster
- name: Wait for Operand Deployment Lifecycle Manager CRD to be ready
  kubernetes.core.k8s_info:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "ibm-common-services"
    name: "{{ operanddeploymentlifecyclemanagerCSV }}"
    field_selectors:
      - metadata.name={{ operanddeploymentlifecyclemanagerCSV }}
  tags: 
    - local-cluster
