---
- name: Create acm-policies namespace
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: acm-policies
  tags: deploy 
- name: Create ibm-operator-catalog-enforce
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      metadata:
        name: ibm-operator-catalog-enforce
        namespace: acm-policies
        annotations:
          policy.open-cluster-management.io/standards: 
          policy.open-cluster-management.io/categories: 
          policy.open-cluster-management.io/controls: 
      spec:
        remediationAction: enforce
        disabled: false
        policy-templates:
          - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                name: ibm-operator-catalog-enforce-prod
              spec:
                remediationAction: enforce
                severity: high
                namespaceSelector:
                  exclude: ["kube-*"]
                  include: ["openshift-marketplace"]
                object-templates:
                  - complianceType: musthave
                    objectDefinition:
                      kind: CatalogSource
                      apiVersion: operators.coreos.com/v1alpha1
                      metadata:
                        name: ibm-operator-catalog
                        namespace: openshift-marketplace
                      spec:
                        displayName: "IBM Operator Catalog" 
                        publisher: IBM
                        sourceType: grpc
                        image: icr.io/cpopen/ibm-operator-catalog:latest
                        updateStrategy:
                          registryPoll:
                            interval: 45m
  tags: deploy 
- name: Create binding-ibm-operator-catalog-enforce
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: PlacementBinding
      metadata:
        name: binding-ibm-operator-catalog-enforce
        namespace: acm-policies
      placementRef:
        name: placement-ibm-operator-catalog-enforce
        kind: PlacementRule
        apiGroup: apps.open-cluster-management.io
      subjects:
      - name: ibm-operator-catalog-enforce
        kind: Policy
        apiGroup: policy.open-cluster-management.io
  tags: deploy 
- name: Create binding-ibm-operator-catalog-enforce
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: PlacementBinding
      metadata:
        name: binding-ibm-operator-catalog-enforce
        namespace: acm-policies
      placementRef:
        name: placement-ibm-operator-catalog-enforce
        kind: PlacementRule
        apiGroup: apps.open-cluster-management.io
      subjects:
      - name: ibm-operator-catalog-enforce
        kind: Policy
        apiGroup: policy.open-cluster-management.io
  tags: deploy
- name: Create placement-ibm-operator-catalog-enforce
  community.kubernetes.k8s:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: apps.open-cluster-management.io/v1
      kind: PlacementRule
      metadata:
        name: placement-ibm-operator-catalog-enforce
        namespace: acm-policies
      spec:
        clusterConditions:
        - status: "True"
          type: ManagedClusterConditionAvailable
        clusterSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
  tags: deploy

- name: Pause for 1 minute ibm-operator Pod is ready
  pause:
    minutes: 1
  tags: deploy

- name: Wait until ibm-operator Pod is ready
  kubernetes.core.k8s_info:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_version: operators.coreos.com/v1alpha1
    kind: CatalogSource
    namespace: openshift-marketplace
    name: ibm-operator-catalog
  register: r_ibm_operator_status3
  ignore_errors: yes
  tags: deploy

- name: Wait until ibm-operator Pod is ready
  kubernetes.core.k8s_info:
    host: "{{ openshift_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    validate_certs: "{{ k8s_validate_certs }}"
    api_version: operators.coreos.com/v1alpha1
    kind: CatalogSource
    namespace: openshift-marketplace
    name: ibm-operator-catalog
  register: r_ibm_operator_status
  ignore_errors: yes
  retries: 30
  delay: 30
  until:
  - r_ibm_operator_status.resources[0].status.connectionState.lastObservedState == "READY"
  tags: deploy
